[package]
name = "ai_translate_unity_localization"
version = "0.1.0"
edition = "2021"

[dependencies]
openai-api-rs = "5.0.10"
rand = "0.8.5"
rand_chacha = "0.3.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = "1.40.0"
